# Based on pydata/xarray
codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: 0.6
    patch:
      default:
        target: 0.6

comment:
#   layout: "diff, flags, files"
#   behavior: once
#   require_base: false